/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AdminConsultationsRouteImport } from './routes/admin/consultations'
import { Route as AdminContactEntriesRouteImport } from './routes/admin/contact-entries'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/admin/account',
  path: '/admin/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsultationsRoute = AdminConsultationsRouteImport.update({
  id: '/admin/consultations',
  path: '/admin/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactEntriesRoute = AdminContactEntriesRouteImport.update({
  id: '/admin/contact-entries',
  path: '/admin/contact-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/contact-entries': typeof AdminContactEntriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/contact-entries': typeof AdminContactEntriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/contact-entries': typeof AdminContactEntriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/services'
    | '/admin'
    | '/admin/account'
    | '/admin/consultations'
    | '/admin/contact-entries'
    | '/admin/login'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/services'
    | '/admin'
    | '/admin/account'
    | '/admin/consultations'
    | '/admin/contact-entries'
    | '/admin/login'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/services'
    | '/admin/_layout'
    | '/admin/account'
    | '/admin/consultations'
    | '/admin/contact-entries'
    | '/admin/login'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminAccountRoute: typeof AdminAccountRoute
  AdminConsultationsRoute: typeof AdminConsultationsRoute
  AdminContactEntriesRoute: typeof AdminContactEntriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/admin/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/consultations': {
      id: '/admin/consultations'
      path: '/admin/consultations'
      fullPath: '/admin/consultations'
      preLoaderRoute: typeof AdminConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contact-entries': {
      id: '/admin/contact-entries'
      path: '/admin/contact-entries'
      fullPath: '/admin/contact-entries'
      preLoaderRoute: typeof AdminContactEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  AdminLayoutRoute: AdminLayoutRoute,
  AdminAccountRoute: AdminAccountRoute,
  AdminConsultationsRoute: AdminConsultationsRoute,
  AdminContactEntriesRoute: AdminContactEntriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
